### PR TITLE
feat: saving checked states

### PR DESCRIPTION
**Pull request by at-the-vr**
Sorry for jumping the gun with this one, got carried away 😆 

reference issue: #1

### CODE REVIEW

**Comment by thomasbnt** [comment]
Ooh that nice ! Thanks you @at-the-vr ! 🙌

**Comment by thomasbnt** [comment]
The script was tested in local?

**Comment by at-the-vr** [comment]
Yeah i TamperMonkey'd the script myself locally. Won't be surprised if stuff's missing out 😅

**Review by thomasbnt — APPROVED** [review]

**Comment by thomasbnt** [comment]
Thank you @at-the-vr for this upgrade 🙌

**Pull request merged**
